### PR TITLE
Add NewWriter

### PR DESCRIPTION
**Pull request by jtolio**
Okay now I've really done it. Maybe I regret everything

### CODE REVIEW

**Comment by zeebo** [comment]
Yeah but why though. Zero values are useful.

**Comment by jtolio** [comment]
yeah i don't know why. if zero values are good why did i do a copy. okay whatever zero value it is

**Comment by zeebo** [comment]
copy at least copies the internal thing. there's no reason to set the internal thing during new though. i scratched my head for a bit on the use case for copy tbh, but whatever.

**Comment by jtolio** [comment]
gotta keep the head scratches goin

**Pull request closed without merging**
